// src/app/javascript/services/application/vue/AppCommon.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue';

import Toasts from '@/services/ui/vue/message/Toasts.vue';
import Loading from '@/services/ui/vue/message/Loading.vue';
import { useToast } from '@/services/ui/vue-hook/useToast';
import { setupMessage } from '@/services/ui/message';

const { toasts, showToast } = useToast();

const isLoading = ref(false);

onMounted(() => {
  setupMessage(showToast, (value: boolean) => {
    isLoading.value = value;
  });
});
</script>

<template>
  <div>
    <Toasts :toasts="toasts" />
    <Loading :isLoading="isLoading" />
  </div>
</template>

// src/app/javascript/services/application/react/AppCommon.tsx
import { useEffect, useState } from 'react';

import Toasts from '@/services/ui/react/message/Toasts';
import Loading from '@/services/ui/react/message/Loading';
import useToast from '@/services/ui/react-hook/useToast';
import { setupMessage } from '@/services/ui/message';

/** アプリケーションの共通部分 */
export default function AppCommon({}) {
  const [toasts, showToast] = useToast();
  const [isLoading, setIsLoading] = useState(false);

  useEffect(() => {
    setupMessage(showToast, setIsLoading);
  }, []);

  return (
    <div>
      <Toasts toasts={toasts} />
      <Loading isLoading={isLoading} />
    </div>
  );
}
